apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - arguswatcher-control-plane.yaml
  - arguswatcher-worker-node.yaml
  - janusguard.yaml

commonLabels:
  compliance: cis-kubernetes
