{{- if and .Values.podDisruptionBudget.enabled (gt (int .Values.controller.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "panoptes-argus.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "panoptes-argus.controller.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "panoptes-argus.controller.selectorLabels" . | nindent 6 }}
{{- end }}
