apiVersion: v1
kind: Service
metadata:
  name: {{ include "panoptes-argus.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "panoptes-argus.controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.observability.prometheus.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "panoptes-argus.controller.selectorLabels" . | nindent 4 }}
